name: "EnvisionBootcamp2021"
output_dir: "docs"
navbar:
  title: "EnvisionBootcamp2021"
  left:
  - text: "Home"
   href: index.html
  - text: "Amplitude Envelope"
   href: extract_AmplitudeEnvelope_Rmarkdown.html
output:
  html_document:
theme: cosmo